name: LeDTeK.at
favicon: null
layout_spectrum: 0.43564259936101735
typography_spectrum: 0.7001380024012178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5408664685674012
  lightness: 0.9531841359566897
  saturation: 0.8178977267816663
  rhythmicContrast: 0.7531587712001055
purpose: []
