name: LeDTeK.at
favicon: null
layout_spectrum: 0.43564259936101735
typography_spectrum: 0.85913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c60248'
    - '#4f4e4e'
    - '#ffffff'
    - '#000000'
    - '#e385a7'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.8178977267816663
  rhythmicContrast: 0.75
purpose: []
